version: '3.8'

services:
  # FastAPI orchestration service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./configs:/configs
      - ./inputs:/inputs
      - ./dist:/dist
      - ./tmp:/tmp
    environment:
      - QDRANT_URL=http://qdrant:6333
      - GROBID_URL=http://grobid:8070
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      - qdrant
      - grobid
      - redis
    command: uvicorn app.apps.api.main:app --host 0.0.0.0 --port 8000 --reload

  # Celery worker for long-running jobs
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./app:/app
      - ./configs:/configs
      - ./inputs:/inputs
      - ./sources:/sources
      - ./dist:/dist
      - ./tmp:/tmp
    environment:
      - QDRANT_URL=http://qdrant:6333
      - GROBID_URL=http://grobid:8070
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - qdrant
      - grobid
    command: celery -A app.apps.worker.celery_app worker --loglevel=info

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:v1.7.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334

  # GROBID for PDF processing
  grobid:
    image: lfoppiano/grobid:0.7.3
    ports:
      - "8070:8070"
    environment:
      - GROBID_MAX_CONNECTIONS=10

  # Redis for Celery broker
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  qdrant_storage:
  redis_data:
