deliverables:
- stems
- upload_mix
length_mode: full
localization:
  enabled: false
  target_languages: []
mix_profile: clean
persona: conversational_educator
promo_count: 3
target_duration_minutes: 60
