# RAG Retrieval Configuration
# Controls knowledge retrieval and grounding

# Embedding model
embed_model: "BAAI/bge-large-en-v1.5"
embed_dimension: 1024
embed_device: "cpu"  # cpu or cuda

# Vector database
db: "faiss"  # faiss or qdrant
db_path: "./tmp/faiss_index"

# Qdrant specific (if db=qdrant)
qdrant:
  url: "http://localhost:6333"
  collection_name: "alexandria_sources"
  distance: "Cosine"

# Retrieval parameters
retrieval:
  top_k: 6              # Initial retrieval count
  min_score: 0.5        # Minimum similarity score
  
  # Re-ranking
  rerank: true
  rerank_model: "BAAI/bge-reranker-large"
  rerank_top_k: 3       # Final count after reranking
  
  # Context window
  max_context_tokens: 4096
  context_overlap: 128

# Chunking strategy for source documents
chunking:
  strategy: "semantic"   # fixed, semantic, sentence
  chunk_size: 512        # tokens
  chunk_overlap: 64      # tokens
  
# Citation generation
citations:
  enabled: true
  format: "apa"          # apa, mla, chicago
  include_page_numbers: true

# Quality thresholds (PRD 3)
quality:
  min_groundedness: 0.8
  min_context_precision: 0.7
  verify_claims: true
